apiVersion: v1
kind: ReplicationController
metadata:
  name: python
spec:
  replicas: 3
  selector:
    app: python
  template:
    metadata:
      name: python
      labels:
        app: python
    spec:
      containers:
      - name: python
        image: sravangdocker/python:test
        imagePullPolicy: IfNotPresent
